ARG BASE_IMAGE
FROM $BASE_IMAGE

# Source: https://github.com/NVIDIA-ISAAC-ROS/isaac-ros-cli/blob/release-4.5/docker/Dockerfile.noble#L243-L246
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y \
    python3-libnvinfer=10.13.2.6-1+cuda13.0 \
    python3-libnvinfer-lean=10.13.2.6-1+cuda13.0 \
    python3-libnvinfer-dispatch=10.13.2.6-1+cuda13.0
