ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y --no-install-recommends \
  git cmake build-essential pkg-config libeigen3-dev gfortran libboost-test-dev

RUN git clone --recursive https://github.com/jrl-umi3218/eigen-quadprog /tmp/eigen-quadprog && \
  cd /tmp/eigen-quadprog && \
  mkdir -p _build && \
  cd _build && \
  cmake .. && \
  make -j"$(nproc)" && \
  ctest --output-on-failure && \
  make install && \
  ldconfig && \
  rm -rf /tmp/eigen-quadprog
