ARG BASE_IMAGE
FROM $BASE_IMAGE

# As of 15 June 2025, the versions of the other dependencies required
# by ultralytics match the packages installed in the x86_64 image.
# "onnx<1.18" for model export.
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install \
    ultralytics \
    "onnx<1.18" \
    onnxslim \
    onnxruntime_gpu
