ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV LOCAL_ENV_FOLDER=environments/multivehicle_sim

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install \
        'fastapi' \
        'uvicorn[standard]' \
        'pydantic-settings'

RUN apt-get purge -y npm \                                                                                                            
      && apt-get autoremove -y \                                                                                                               
      && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \                                                                           
      && apt-get install -y nodejs \                                                                                                           
      && rm -rf /var/lib/apt/lists/*  
