set -g mouse on
set -g pane-border-status top
set-option -g default-shell /bin/bash
set-option -g set-clipboard on
set -g default-terminal "screen-256color"
bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard"
