ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  apt-get update -y || true && \
  apt-get install -y \
  ccache

ENV CCACHE_DIR=/home/${USERNAME}/.cache/ccache
ENV CC=/usr/lib/ccache/gcc
ENV CXX=/usr/lib/ccache/g++
