ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG ROS_DISTRO=jazzy

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update -y || true && \
  apt-get install -y \
  # OpenCV
  python3-opencv \
  # Isaac ROS vision utils
  ros-${ROS_DISTRO}-isaac-ros-test \
  ros-${ROS_DISTRO}-isaac-ros-argus-camera \
  ros-${ROS_DISTRO}-isaac-ros-image-pipeline \
  # Compression
  ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
  ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
  # YOLO
  ros-${ROS_DISTRO}-isaac-ros-yolov8 \
  ros-${ROS_DISTRO}-isaac-ros-tensor-rt \
  ros-${ROS_DISTRO}-isaac-ros-dnn-image-encoder \
  ros-${ROS_DISTRO}-isaac-ros-nitros-detection2-d-array-type \
  ros-${ROS_DISTRO}-isaac-ros-triton \
  # Foxglove
  ros-${ROS_DISTRO}-foxglove-bridge

# NOTES:
# isaac_ros_test is required when building Isaac ROS packages from source.
